version: "3.9"

services:
  # MongoDB service
  database:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

  # Node.js service
  node:
    image: node:18-alpine
    restart: always
    container_name: nodejs
    depends_on:
      - database
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DATABASE_URL: mongodb://admin:admin@database:27017/
    ports:
      - 3000:3000
    command: sh -c 'npm install && npm run dev'

volumes:
  mongo_data:
